messages: #{message_group}: place the name of message_group used in the command
  reload_exit: "Grupo de mensajes actualizado"
  reload_error: "Hubo un error al recargar el grupo de mensajes"
  stop_exit: "El grupo de mensajes {message_group} se pausó"
  stop_error: "El grupo de mensajes {message_group} no existe o ya está pausado"
  start_exit: "El grupo de mensajes {message_group} se reanudó"
  start_error: "El grupo de mensajes {message_group} no existe o ya está reanudado"
  unknown_command: "Comando no reconocido"
cooldown: #this cooldown its for EVERY command in the plugin
  announcer: 5 #seconds